import tkinter as tk
nombreDeUsuarioRegistrado=('Darka')
contrasenaRegistrada=('123456')
ventana = tk.Tk()
ventana.title('Log in')
ventana.geometry('200x300+600+500')
ventana.config(bg=("#19ABFF"))
etiquetaUsuario= tk.Label(text='Ingrese su nombre de usuario.',bg="#A0EEFC")
etiquetaUsuario.pack(pady='5')
entradaUsuario= tk.Entry(width=30)
entradaUsuario.get()
entradaUsuario.pack(pady=20)
etiquetaContraseña=tk.Label(text='Ingrese su contraseña.',bg="#A0EEFC")
etiquetaContraseña.pack(pady=5)
entradaContraseña=tk.Entry(width=30)
entradaContraseña.pack(pady=20)
entradaContraseña.get()
def validar():
    usuario=entradaUsuario.get()
    contraseña=entradaContraseña.get()
    if usuario and contraseña == nombreDeUsuarioRegistrado and contrasenaRegistrada:
        resultado.config(text='Ingreso exitoso')
    else:
        resultado.config(text='Acceso denegado')
boton1=tk.Button(text='log in', bg='blue', command=validar)
boton1.pack(pady=5)
resultado=tk.Label(text='')
resultado.pack()
ventana.mainloop()
