import tkinter as tk
from classFraccion import Fraccion
ventana=tk.Tk()
ventana.title('Sumador de Fracciones')
ventana.geometry('500x500+0+0')
ventana.config(bg='#FFFFFF')
etiquetaFraccion1=tk.Label(text='Fracción1', bg="#BBBBBB")
etiquetaFraccion1.pack(pady=30)
entradaNum1=tk.Entry(width=5)
entradaNum1.get()
entradaNum1.pack()
etiquetaBarra=tk.Label(text='/',bg='#FFFFFF')
etiquetaBarra.pack()
entradaDenom1=tk.Entry(width=5)
entradaDenom1.get()
entradaDenom1.pack()
etiquetaFraccion2=tk.Label(text='Fracción2', bg='#BBBBBB')
etiquetaFraccion2.pack(pady=30)
entradaNum2=tk.Entry(width=5)
entradaNum2.get()
entradaNum2.pack()
etiquetaBarra=tk.Label(text='/',bg='#FFFFFF')
etiquetaBarra.pack()
entradaDenom2=tk.Entry(width=5)
entradaDenom2.get()
entradaDenom2.pack()
def sumar():
  num1=int(entradaNum1.get())
  denom1=int(entradaDenom1.get())
  num2=int(entradaNum2.get())
  denom2=int(entradaDenom2.get())
  fr1=Fraccion(num1,denom2)
  fr2=Fraccion(num2, denom2)
  result=fr1+fr2
  etiquetaResult.config(text=f'{result}')
botonSumador=tk.Button(text='Sumar', command=sumar, bg='#BBBBBB')
botonSumador.pack()
etiquetaResult=tk.Label(text='')
etiquetaResult.pack()
ventana.mainloop()

'''fr1=Fraccion(1, 3)
fr2=Fraccion(2, 3)
result=fr1+fr2'''
#result=fr1.sumar(fr2)
#print (result)